<?php

/**
 * RAMP: Records and Activity Management Program
 *
 * LICENSE
 *
 * This source file is subject to the BSD-2-Clause license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.cs.kzoo.edu/ramp/LICENSE.txt
 *
 * @category   Ramp
 * @package    Ramp_Views
 * @copyright  Copyright (c) 2012-2014 Alyce Brady
 *             (http://www.cs.kzoo.edu/~abrady)
 * @license    http://www.cs.kzoo.edu/ramp/LICENSE.txt   Simplified BSD License
 *
 */

/* This helper script expects an array of button labels.
*/

// Technique for turning button labels into valid name identifiers taken
// from Zend_Form_Element.
$charset = '^a-zA-Z0-9_\x7f-\xff';
?>

<fieldset id="button-list">
<div id='tableActions' class="btn-group btn-group-vertical pull-right">

<?php
$class = $this->firstButtonIsPrimary ? 'btn btn-primary' : 'btn';
foreach ( $this->buttonList as $buttonLabel ) :
    $buttonType = ( $buttonLabel == TableController::RESET_BUTTON ) ?
                        "reset" : "submit";
    $buttonLabel = $this->escape($buttonLabel);
    $buttonId = $this->escape(preg_replace('/[' . $charset . ']/', '', 
                                    (string) $buttonLabel));
    echo "<input type='$buttonType' name='submit' id='$buttonId'
            value='$buttonLabel' class='$class' />\n";
    $class = 'btn';
endforeach;
?>

</div>
</fieldset>

